# Model Deployment Configuration
model_registry:
  registered_name: "EfficientNet_Defect_Detector"
  version: 1

# Image Preprocessing Configuration
data_preprocessing:
  target_size: [224, 224]
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  